import { Hono } from "hono";
import { cors } from "hono/cors";
import type { GetHealthUseCase } from "../../application/health/GetHealthUseCase";
import { registerHealthRoutes } from "./routes/health.route";
import type { CreateCourseUseCase } from "../../application/course/CreateCourseUseCase";
import type { GetCourseByIdUseCase } from "../../application/course/GetCourseByIdUseCase";
import type { ListCoursesUseCase } from "../../application/course/ListCoursesUseCase";
import type { UpdateCourseUseCase } from "../../application/course/UpdateCourseUseCase";
import type { DeleteCourseUseCase } from "../../application/course/DeleteCourseUseCase";
import { registerCourseRoutes } from "./routes/course.route";
import type { CreateAssignmentUseCase } from "../../application/assignment/CreateAssignmentUseCase";
import type { GetAssignmentByIdUseCase } from "../../application/assignment/GetAssignmentByIdUseCase";
import type { ListAssignmentsUseCase } from "../../application/assignment/ListAssignmentsUseCase";
import type { UpdateAssignmentUseCase } from "../../application/assignment/UpdateAssignmentUseCase";
import type { DeleteAssignmentUseCase } from "../../application/assignment/DeleteAssignmentUseCase";
import type { CompleteAssignmentUseCase } from "../../application/assignment/CompleteAssignmentUseCase";
import type { ConfirmCompleteAssignmentUseCase } from "../../application/assignment/ConfirmCompleteAssignmentUseCase";
import type { UncompleteAssignmentUseCase } from "../../application/assignment/UncompleteAssignmentUseCase";
import type { RescheduleAssignmentUseCase } from "../../application/assignment/RescheduleAssignmentUseCase";
import type { WrapUpAssignmentUseCase } from "../../application/assignment/WrapUpAssignmentUseCase";
import type { WrapUpLateAssignmentUseCase } from "../../application/assignment/WrapUpLateAssignmentUseCase";
import { registerAssignmentRoutes } from "./routes/assignment.route";
import type { ListAssignmentStatesUseCase } from "../../application/assignmentState/ListAssignmentStatesUseCase";
import { registerAssignmentStateRoutes } from "./routes/assignmentState.route";
import type { CreateWorkSessionUseCase } from "../../application/workSession/CreateWorkSessionUseCase";
import type { GetWorkSessionByIdUseCase } from "../../application/workSession/GetWorkSessionByIdUseCase";
import type { ListWorkSessionsUseCase } from "../../application/workSession/ListWorkSessionsUseCase";
import type { CompleteWorkSessionUseCase } from "../../application/workSession/CompleteWorkSessionUseCase";
import type { ConfirmCompleteWorkSessionUseCase } from "../../application/workSession/ConfirmCompleteWorkSessionUseCase";
import type { ConfirmSkipWorkSessionUseCase } from "../../application/workSession/ConfirmSkipWorkSessionUseCase";
import type { UncompleteWorkSessionUseCase } from "../../application/workSession/UncompleteWorkSessionUseCase";
import type { DeleteWorkSessionUseCase } from "../../application/workSession/DeleteWorkSessionUseCase";
import type { WrapUpLateWorkSessionUseCase } from "../../application/workSession/WrapUpLateWorkSessionUseCase";
import type { RescheduleWorkSessionUseCase } from "../../application/workSession/RescheduleWorkSessionUseCase";
import type { EditWorkSessionUseCase } from "../../application/workSession/EditWorkSessionUseCase";
import type { CloseWorkSessionUseCase } from "../../application/workSession/CloseWorkSessionUseCase";
import type { GetRandomWorkSessionCompletionMessageUseCase } from "../../application/workSession/GetRandomWorkSessionCompletionMessageUseCase";
import { registerWorkSessionRoutes } from "./routes/workSession.route";
import type { ListWorkSessionStatesUseCase } from "../../application/workSessionState/ListWorkSessionStatesUseCase";
import { registerWorkSessionStateRoutes } from "./routes/workSessionState.route";
import type { CreateAssignmentWorkSessionUseCase } from "../../application/assignmentWorkSession/CreateAssignmentWorkSessionUseCase";
import type { GetAssignmentWorkSessionByIdUseCase } from "../../application/assignmentWorkSession/GetAssignmentWorkSessionByIdUseCase";
import type { ListAssignmentWorkSessionsUseCase } from "../../application/assignmentWorkSession/ListAssignmentWorkSessionsUseCase";
import type { UpdateAssignmentWorkSessionUseCase } from "../../application/assignmentWorkSession/UpdateAssignmentWorkSessionUseCase";
import type { DeleteAssignmentWorkSessionUseCase } from "../../application/assignmentWorkSession/DeleteAssignmentWorkSessionUseCase";
import type { MarkAssignmentWorkedOnUseCase } from "../../application/assignmentWorkSession/MarkAssignmentWorkedOnUseCase";
import type { UnmarkAssignmentWorkedOnUseCase } from "../../application/assignmentWorkSession/UnmarkAssignmentWorkedOnUseCase";
import { registerAssignmentWorkSessionRoutes } from "./routes/assignmentWorkSession.route";
import type { ListNotificationsUseCase } from "../../application/notification/ListNotificationsUseCase";
import type { MarkNotificationReadUseCase } from "../../application/notification/MarkNotificationReadUseCase";
import type { GetNotificationByIdUseCase } from "../../application/notification/GetNotificationByIdUseCase";
import type { RemoveNotificationUseCase } from "../../application/notification/RemoveNotificationUseCase";
import { registerNotificationRoutes } from "./routes/notification.route";

export interface ServerDeps {
  getHealthUseCase: GetHealthUseCase;
  createCourseUseCase: CreateCourseUseCase;
  getCourseByIdUseCase: GetCourseByIdUseCase;
  listCoursesUseCase: ListCoursesUseCase;
  updateCourseUseCase: UpdateCourseUseCase;
  deleteCourseUseCase: DeleteCourseUseCase;
  createAssignmentUseCase: CreateAssignmentUseCase;
  getAssignmentByIdUseCase: GetAssignmentByIdUseCase;
  listAssignmentsUseCase: ListAssignmentsUseCase;
  updateAssignmentUseCase: UpdateAssignmentUseCase;
  deleteAssignmentUseCase: DeleteAssignmentUseCase;
  completeAssignmentUseCase: CompleteAssignmentUseCase;
  confirmCompleteAssignmentUseCase: ConfirmCompleteAssignmentUseCase;
  uncompleteAssignmentUseCase: UncompleteAssignmentUseCase;
  rescheduleAssignmentUseCase: RescheduleAssignmentUseCase;
  wrapUpAssignmentUseCase: WrapUpAssignmentUseCase;
  wrapUpLateAssignmentUseCase: WrapUpLateAssignmentUseCase;
  listAssignmentStatesUseCase: ListAssignmentStatesUseCase;
  createWorkSessionUseCase: CreateWorkSessionUseCase;
  getWorkSessionByIdUseCase: GetWorkSessionByIdUseCase;
  listWorkSessionsUseCase: ListWorkSessionsUseCase;
  completeWorkSessionUseCase: CompleteWorkSessionUseCase;
  confirmCompleteWorkSessionUseCase: ConfirmCompleteWorkSessionUseCase;
  confirmSkipWorkSessionUseCase: ConfirmSkipWorkSessionUseCase;
  uncompleteWorkSessionUseCase: UncompleteWorkSessionUseCase;
  deleteWorkSessionUseCase: DeleteWorkSessionUseCase;
  wrapUpLateWorkSessionUseCase: WrapUpLateWorkSessionUseCase;
  rescheduleWorkSessionUseCase: RescheduleWorkSessionUseCase;
  editWorkSessionUseCase: EditWorkSessionUseCase;
  closeWorkSessionUseCase: CloseWorkSessionUseCase;
  getRandomWorkSessionCompletionMessageUseCase: GetRandomWorkSessionCompletionMessageUseCase;
  listWorkSessionStatesUseCase: ListWorkSessionStatesUseCase;
  createAssignmentWorkSessionUseCase: CreateAssignmentWorkSessionUseCase;
  getAssignmentWorkSessionByIdUseCase: GetAssignmentWorkSessionByIdUseCase;
  listAssignmentWorkSessionsUseCase: ListAssignmentWorkSessionsUseCase;
  updateAssignmentWorkSessionUseCase: UpdateAssignmentWorkSessionUseCase;
  deleteAssignmentWorkSessionUseCase: DeleteAssignmentWorkSessionUseCase;
  markAssignmentWorkedOnUseCase: MarkAssignmentWorkedOnUseCase;
  unmarkAssignmentWorkedOnUseCase: UnmarkAssignmentWorkedOnUseCase;
  listNotificationsUseCase: ListNotificationsUseCase;
  markNotificationReadUseCase: MarkNotificationReadUseCase;
  getNotificationByIdUseCase: GetNotificationByIdUseCase;
  removeNotificationUseCase: RemoveNotificationUseCase;
  allowedOrigins: string[];
}

export function createServer(deps: ServerDeps): Hono {
  const app = new Hono();
  app.use("*", cors({ origin: deps.allowedOrigins }));
  registerHealthRoutes(app, deps);
  registerCourseRoutes(app, deps);
  registerAssignmentRoutes(app, deps);
  registerAssignmentStateRoutes(app, deps);
  registerWorkSessionRoutes(app, deps);
  registerWorkSessionStateRoutes(app, deps);
  registerAssignmentWorkSessionRoutes(app, deps);
  registerNotificationRoutes(app, deps);
  return app;
}
