import { Hono } from "hono";
import { cors } from "hono/cors";
import type { GetHealthUseCase } from "../../application/health/GetHealthUseCase";
import { registerHealthRoutes } from "./routes/health.route";
import type { CreateCourseUseCase } from "../../application/course/CreateCourseUseCase";
import type { GetCourseByIdUseCase } from "../../application/course/GetCourseByIdUseCase";
import type { ListCoursesUseCase } from "../../application/course/ListCoursesUseCase";
import type { UpdateCourseUseCase } from "../../application/course/UpdateCourseUseCase";
import type { DeleteCourseUseCase } from "../../application/course/DeleteCourseUseCase";
import { registerCourseRoutes } from "./routes/course.route";
import type { CreateAssignmentUseCase } from "../../application/assignment/CreateAssignmentUseCase";
import type { GetAssignmentByIdUseCase } from "../../application/assignment/GetAssignmentByIdUseCase";
import type { ListAssignmentsUseCase } from "../../application/assignment/ListAssignmentsUseCase";
import type { UpdateAssignmentUseCase } from "../../application/assignment/UpdateAssignmentUseCase";
import type { DeleteAssignmentUseCase } from "../../application/assignment/DeleteAssignmentUseCase";
import type { ChangeAssignmentStateUseCase } from "../../application/assignment/ChangeAssignmentStateUseCase";
import { registerAssignmentRoutes } from "./routes/assignment.route";
import type { ListAssignmentStatesUseCase } from "../../application/assignmentState/ListAssignmentStatesUseCase";
import { registerAssignmentStateRoutes } from "./routes/assignmentState.route";
import type { CreateWorkSessionUseCase } from "../../application/workSession/CreateWorkSessionUseCase";
import type { GetWorkSessionByIdUseCase } from "../../application/workSession/GetWorkSessionByIdUseCase";
import type { ListWorkSessionsUseCase } from "../../application/workSession/ListWorkSessionsUseCase";
import type { ChangeWorkSessionStateUseCase } from "../../application/workSession/ChangeWorkSessionStateUseCase";
import type { DeleteWorkSessionUseCase } from "../../application/workSession/DeleteWorkSessionUseCase";
import type { RescheduleWorkSessionUseCase } from "../../application/workSession/RescheduleWorkSessionUseCase";
import { registerWorkSessionRoutes } from "./routes/workSession.route";
import type { ListWorkSessionStatesUseCase } from "../../application/workSessionState/ListWorkSessionStatesUseCase";
import { registerWorkSessionStateRoutes } from "./routes/workSessionState.route";
import type { CreateAssignmentWorkSessionUseCase } from "../../application/assignmentWorkSession/CreateAssignmentWorkSessionUseCase";
import type { GetAssignmentWorkSessionByIdUseCase } from "../../application/assignmentWorkSession/GetAssignmentWorkSessionByIdUseCase";
import type { ListAssignmentWorkSessionsUseCase } from "../../application/assignmentWorkSession/ListAssignmentWorkSessionsUseCase";
import type { UpdateAssignmentWorkSessionUseCase } from "../../application/assignmentWorkSession/UpdateAssignmentWorkSessionUseCase";
import type { DeleteAssignmentWorkSessionUseCase } from "../../application/assignmentWorkSession/DeleteAssignmentWorkSessionUseCase";
import { registerAssignmentWorkSessionRoutes } from "./routes/assignmentWorkSession.route";

export interface ServerDeps {
  getHealthUseCase: GetHealthUseCase;
  createCourseUseCase: CreateCourseUseCase;
  getCourseByIdUseCase: GetCourseByIdUseCase;
  listCoursesUseCase: ListCoursesUseCase;
  updateCourseUseCase: UpdateCourseUseCase;
  deleteCourseUseCase: DeleteCourseUseCase;
  createAssignmentUseCase: CreateAssignmentUseCase;
  getAssignmentByIdUseCase: GetAssignmentByIdUseCase;
  listAssignmentsUseCase: ListAssignmentsUseCase;
  updateAssignmentUseCase: UpdateAssignmentUseCase;
  deleteAssignmentUseCase: DeleteAssignmentUseCase;
  changeAssignmentStateUseCase: ChangeAssignmentStateUseCase;
  listAssignmentStatesUseCase: ListAssignmentStatesUseCase;
  createWorkSessionUseCase: CreateWorkSessionUseCase;
  getWorkSessionByIdUseCase: GetWorkSessionByIdUseCase;
  listWorkSessionsUseCase: ListWorkSessionsUseCase;
  changeWorkSessionStateUseCase: ChangeWorkSessionStateUseCase;
  deleteWorkSessionUseCase: DeleteWorkSessionUseCase;
  rescheduleWorkSessionUseCase: RescheduleWorkSessionUseCase;
  listWorkSessionStatesUseCase: ListWorkSessionStatesUseCase;
  createAssignmentWorkSessionUseCase: CreateAssignmentWorkSessionUseCase;
  getAssignmentWorkSessionByIdUseCase: GetAssignmentWorkSessionByIdUseCase;
  listAssignmentWorkSessionsUseCase: ListAssignmentWorkSessionsUseCase;
  updateAssignmentWorkSessionUseCase: UpdateAssignmentWorkSessionUseCase;
  deleteAssignmentWorkSessionUseCase: DeleteAssignmentWorkSessionUseCase;
  allowedOrigins: string[];
}

export function createServer(deps: ServerDeps): Hono {
  const app = new Hono();
  app.use("*", cors({ origin: deps.allowedOrigins }));
  registerHealthRoutes(app, deps);
  registerCourseRoutes(app, deps);
  registerAssignmentRoutes(app, deps);
  registerAssignmentStateRoutes(app, deps);
  registerWorkSessionRoutes(app, deps);
  registerWorkSessionStateRoutes(app, deps);
  registerAssignmentWorkSessionRoutes(app, deps);
  return app;
}
